port: 8000

stocks_cn:
  - code: "600519"
  - code: "000858"
  - code: "510300"
  - code: "159915"

crypto:
  - name: "比特币"
    symbol: "BTCUSDT"
  - name: "以太坊"
    symbol: "ETHUSDT"
  - name: "Solana"
    symbol: "SOLUSDT"
